image: node:12

stages:
    - build
    - deploy

.app_build_template: &app_job_definition
    stage: build
    tags:
        - c19data
    before_script:
        - npm ci && npm cache verify
    artifacts:
        paths:
        - build

.app_deploy_template: &app_deploy_definition
    image: 608395931184.dkr.ecr.us-east-1.amazonaws.com/ci/python-aws-cli:latest
    stage: deploy
    tags:
        - c19data
    script:
        ## Sync only the static build folder to the S3 bucket
        - aws s3 sync ./build s3://${S3_DEPLOY_BUCKET}/${CI_PROJECT_NAME}/ --delete

build:stage:
    <<: *app_job_definition
    only:
      - develop
    variables:
        PUBLIC_URL: "${STAGE_URL}"
    script:
        - PUBLIC_URL=${PUBLIC_URL}  NODE_ENV=production CI=false npm run build
    environment:
        name: Stage

build:prod:
    <<: *app_job_definition
    only:
        refs:
        - tags
        - master
        variables:
        - $CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+(?:-(?:alpha|beta))?$/
    except:
        refs:
        - branches
        - develop
    variables:
      PUBLIC_URL: "${PROD_URL}"     
    script:
        - PUBLIC_URL=${PUBLIC_URL}  NODE_ENV=production CI=false npm run build
    environment:
        name: production

deploy:stage:
    <<: *app_deploy_definition
    only:
      - develop
    environment:
        name: Stage
    variables:
        S3_DEPLOY_BUCKET: "${STAGE_S3_DEPLOY_BUCKET}"
        AWS_ACCESS_KEY_ID: "${STAGE_ACCESS_KEY}"
        AWS_SECRET_ACCESS_KEY: "${STAGE_ACCESS_SECRET}"
    dependencies:
        - build:stage

deploy:prod:
    <<: *app_deploy_definition
    only:
        refs:
        - tags
        - master
        variables:
        - $CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+(?:-(?:alpha|beta))?$/
    except:
        refs:
        - branches
        - develop
    when: manual
    environment:
        name: production
    variables:
        S3_DEPLOY_BUCKET: "${PROD_S3_DEPLOY_BUCKET}"
        AWS_ACCESS_KEY_ID: "${PROD_ACCESS_KEY}"
        AWS_SECRET_ACCESS_KEY: "${PROD_ACCESS_SECRET}"
    dependencies:
        - build:prod